### PR TITLE
fix ajv import

### LINKED ISSUE #876: Ajv import in TypeScript extension bazaar facilitator is missing file extension
When running a server which imports the `@x402/extensions/bazaar` module using Node’s native ESM loader, you get the following error:

```
node:internal/modules/run_main:107
    triggerUncaughtException(
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../node_modules/.pnpm/@x402+extensions@2.1.0/node_modules/ajv/dist/2020' imported from .../node_modules/.pnpm/@x402+extensions@2.1.0/node_modules/@x402/extensions/dist/esm/chunk-STXY3Q5R.mjs
Did you mean to import "ajv/dist/2020.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:864:10)
    at defaultResolve (node:internal/modules/esm/resolve:990:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:712:20)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:729:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:758:52)
    at #resolve (node:internal/modules/esm/loader:694:17)
    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:614:35)
    at ModuleJob.syncLink (node:internal/modules/esm/module_job:143:33)
    at ModuleJob.link (node:internal/modules/esm/module_job:228:17) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///.../node_modules/.pnpm/@x402+extensions@2.1.0/node_modules/ajv/dist/2020'
}
```

This is because the import here https://github.com/coinbase/x402/blob/main/typescript/packages/extensions/src/bazaar/facilitator.ts#L10 is missing the .js file extension in the published ESM build, which is required when using Node’s native ESM loader. Adding the .js file extension to `import Ajv from "ajv/dist/2020";`, resolves this issue.

### PR DESCRIPTION
**Pull request by phdargen**
## Description

Fixes a build issue for next projects using the Bazaar discovery extensions:
```
@x402/next-example:build: Failed to load bazaar extension: Error: Cannot find module 'x402/typescript/packages/extensions/node_modules/ajv/dist/2020' imported from 402/typescript/packages/extensions/dist/esm/chunk-STXY3Q5R.mjs
@x402/next-example:build: Did you mean to import "ajv/dist/2020.js"?
@x402/next-example:build:     at ignore-listed frames {
@x402/next-example:build:   code: 'ERR_MODULE_NOT_FOUND',
@x402/next-example:build:   url: 'file:///x402/typescript/packages/extensions/node_modules/ajv/dist/2020'
```

Closes https://github.com/coinbase/x402/issues/876

## Checklist

- [x] I have formatted and linted my code
- [x] All new and existing tests pass
- [x] My commits are signed (required for merge) -- you may need to rebase if you initially pushed unsigned commits

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by CarsonRoscoe — APPROVED** [review]

File: typescript/packages/extensions/src/bazaar/facilitator.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@
  * Supports both v2 (extensions in PaymentRequired) and v1 (outputSchema in PaymentRequirements).
  */
 
-import Ajv from "ajv/dist/2020";
+import Ajv from "ajv/dist/2020.js";
```
Comment (CarsonRoscoe) [inline typescript/packages/extensions/src/bazaar/facilitator.ts:10]: Actually, /dist should not be read from.

Can you investigate if this can be done without reading from /dist? @phdargen

Comment (phdargen) [reply typescript/packages/extensions/src/bazaar/facilitator.ts:10]: This seems to be the only way to import `JSON Schema draft-2020-12`, see https://ajv.js.org/json-schema.html#draft-2020-12

As an alternative we could switch to `draft-07` with this import `import Ajv from "ajv";`
This would require changing: `"$schema": "https://json-schema.org/draft/2020-12/schema"` -> `$schema: "http://json-schema.org/draft-07/schema#"` in:

- typescript/packages/extensions/src/bazaar/resourceService.ts
- typescript/packages/extensions/src/bazaar/types.ts
- go/extensions/bazaar/resource_service.go

Let me know what you prefer @CarsonRoscoe

**Review by CarsonRoscoe — APPROVED** [review]
