### PR TITLE
fix(python): handle invalid facilitator responses

### LINKED ISSUE #545: Python: Middleware sometimes produces 500 errors.
https://github.com/coinbase/x402/blob/main/python/x402/src/x402/facilitator.py#L67

When this line calls `VerifyResponse(**data)`, if a missing field is encountered, it generates a validation error. Since the upper layer does not catch the exception here, it causes the middleware to return an HTTP 500 error.

### PR DESCRIPTION
**Pull request by ziyangliu-666**
## Description

Closes #545.

Handle malformed facilitator responses in the Python HTTP client and middleware so they return a stable `502` instead of surfacing as `500`.

This change:
- adds a dedicated `FacilitatorResponseError` for invalid facilitator JSON and schema-invalid responses
- wraps facilitator response parsing in the Python HTTP client for `verify`, `settle`, and `get_supported`
- maps facilitator boundary errors to `502 Bad Gateway` in both FastAPI and Flask middleware
- adds regression coverage for invalid JSON and schema-invalid facilitator responses

## Tests

- `uv run --project python/x402 ruff check python/x402/http/facilitator_client.py python/x402/http/facilitator_client_base.py python/x402/http/middleware/fastapi.py python/x402/http/middleware/flask.py python/x402/tests/unit/http/test_facilitator_client.py python/x402/tests/unit/http/middleware/test_fastapi.py python/x402/tests/unit/http/middleware/test_flask.py`
- `uv run --project python/x402 pytest python/x402/tests/unit/http/test_facilitator_client.py python/x402/tests/unit/http/middleware/test_fastapi.py python/x402/tests/unit/http/middleware/test_flask.py`

## Checklist

- [x] I have formatted and linted my code
- [x] All new and existing tests pass
- [x] My commits are signed (required for merge)
- [x] I added a changelog fragment for user-facing changes

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by ethanoroshiba** [comment]
Thanks for the fix! Just wanted to see before doing a full review: the same issue appears to exist in Go/Typescript too (wrong semantics on `verify`/`settle`, and unhandled exceptions from `getSupported` during init in the TS Express middleware). Would love to see those changes as a part of this PR or a follow-up if you're open to it, if not I can ticket separately as well.

**Comment by ziyangliu-666** [comment]
Thanks for flagging this. I went ahead and included the Go/TypeScript follow-up in this PR in 5a6008e and 5c25257, and
  ran the Go slice locally as well.

  Included:
  - Go HTTP facilitator client now treats malformed success payloads from `verify`/`settle`/`getSupported` as
  facilitator boundary errors instead of normal payment failures.
  - TypeScript HTTP facilitator client does the same for `verify`/`settle`/`getSupported`.
  - TypeScript core/http server now preserves `FacilitatorResponseError` through verify/settle so framework middleware
  can return `502` instead of flattening those into `402` payment errors.
  - Express lazy init now catches facilitator init failures from `getSupported`; I also applied the same handling to
  Hono/Next while touching the shared wrappers.

  Verified with:
  - `go test ./http -run 'TestHTTPFacilitatorClient|TestGetSupported'`
  - `pnpm --filter @x402/core test -- test/unit/http/httpFacilitatorClient.test.ts test/unit/http/
  x402HTTPResourceServer.errors.test.ts test/unit/server/x402ResourceServer.test.ts test/unit/http/
  x402HTTPResourceServer.initialize.test.ts`
  - `pnpm --filter @x402/express test -- src/index.test.ts`
  - `pnpm --filter @x402/next test -- src/index.test.ts src/utils.test.ts`
  - `pnpm --filter @x402/hono exec vitest run src/index.test.ts src/adapter.test.ts --exclude src/
  malformedPathBypass.test.ts`

File: typescript/packages/http/express/src/index.ts [hunk 1]
```diff
@@ -44,6 +45,23 @@ export interface SchemeRegistration {
...
+  while (current instanceof Error) {
+    if (current instanceof FacilitatorResponseError) {
+      return current;
+    }
+    current = current.cause;
+  }
+
+  return null;
+}
+
```
Comment (ethanoroshiba) [inline typescript/packages/http/express/src/index.ts]: This helper exists across 3 packages: `express/src`, `hono/src`, `next/src`. I think it'd be good to consolidate to shared functionality within `@x402/core` to uphold DRY principle.

File: typescript/packages/http/express/src/index.ts [hunk 2]
```diff
@@ -113,7 +131,16 @@ export function paymentMiddlewareFromHTTPServer(
 
     // Only initialize when processing a protected route
     if (initPromise) {
-      await initPromise;
+      try {
+        await initPromise;
+      } catch (error) {
+        const facilitatorError = getFacilitatorResponseError(error);
```
Comment (ethanoroshiba) [inline typescript/packages/http/express/src/index.ts:153]: If we don't set the `initPromise` to null on failure case, it will return the same error every time instead of retrying on the next request.
```suggestion
        const facilitatorError = getFacilitatorResponseError(error);
        initPromise = null;
```

File: go/http/facilitator_client.go [hunk 3]
```diff
@@ -67,6 +68,150 @@ const getSupportedRetries = 3
...
+	return values
+}
+
+func nonNilSigners(signers map[string][]string) map[string][]string {
+	if signers == nil {
+		return map[string][]string{}
+	}
+	return signers
+}
+
```
Comment (ethanoroshiba) [inline go/http/facilitator_client.go]: nit: I think the single-use helpers here might be a bit overkill, the extra level of indirection can cause a bit of confusion. Personally, I'd prefer to move the checks into the calling function.

File: go/http/facilitator_client.go [hunk 4]
```diff
@@ -67,6 +68,150 @@ const getSupportedRetries = 3
...
+		return x402.SupportedResponse{}, newFacilitatorResponseError("getSupported", "JSON", body, err)
+	}
+	kinds := make([]x402.SupportedKind, 0, len(response.Kinds))
+	for _, kind := range response.Kinds {
+		if kind.X402Version == nil || kind.Scheme == "" || kind.Network == "" {
+			return x402.SupportedResponse{}, newFacilitatorResponseError(
+				"getSupported",
+				"data",
+				body,
+				fmt.Errorf("invalid supported kind"),
```
Comment (ethanoroshiba) [inline go/http/facilitator_client.go]: I think this error message could be slightly misleading and diverges from the example above
```suggestion
				fmt.Errorf("missing required fields"),
```

File: typescript/packages/http/hono/src/index.ts [hunk 5]
```diff
@@ -113,7 +131,15 @@ export function paymentMiddlewareFromHTTPServer(
 
     // Only initialize when processing a protected route
     if (initPromise) {
-      await initPromise;
+      try {
+        await initPromise;
+      } catch (error) {
+        const facilitatorError = getFacilitatorResponseError(error);
```
Comment (ethanoroshiba) [inline typescript/packages/http/hono/src/index.ts:154]:
```suggestion
        const facilitatorError = getFacilitatorResponseError(error);
        initPromise = null;
```

File: typescript/packages/http/hono/src/index.ts [hunk 6]
```diff
@@ -44,6 +45,23 @@ export interface SchemeRegistration {
...
 }
 
+function getFacilitatorResponseError(error: unknown): FacilitatorResponseError | null {
+  let current = error;
+
+  while (current instanceof Error) {
+    if (current instanceof FacilitatorResponseError) {
+      return current;
+    }
+    current = current.cause;
```
Comment (ethanoroshiba) [inline typescript/packages/http/hono/src/index.ts]: `pnpm build` fails on this line for me. `Error.cause` requires ES2022+, but lib is set to ES2020. I would bump lib (but not target) to ES2022 here in the base config so that way the build passes but we don't risk unintentionally changing any runtime behavior.

File: typescript/packages/core/src/http/httpFacilitatorClient.ts [hunk 7]
```diff
@@ -108,17 +198,23 @@ export class HTTPFacilitatorClient implements FacilitatorClient {
...
     });
 
-    const data = await response.json();
+    if (!response.ok) {
+      const text = await response.text();
+      let data: unknown;
+      try {
+        data = JSON.parse(text);
+      } catch {
+        throw new Error(`Facilitator verify failed (${response.status}): ${text}`);
```
Comment (ethanoroshiba) [inline typescript/packages/core/src/http/httpFacilitatorClient.ts]: I think we should use `responseExcerpt` here

File: typescript/packages/core/src/http/httpFacilitatorClient.ts [hunk 8]
```diff
@@ -151,17 +247,23 @@ export class HTTPFacilitatorClient implements FacilitatorClient {
...
     });
 
-    const data = await response.json();
+    if (!response.ok) {
+      const text = await response.text();
+      let data: unknown;
+      try {
+        data = JSON.parse(text);
+      } catch {
+        throw new Error(`Facilitator settle failed (${response.status}): ${text}`);
```
Comment (ethanoroshiba) [inline typescript/packages/core/src/http/httpFacilitatorClient.ts]: I think we should use `responseExcerpt` here

File: go/http/facilitator_client.go [hunk 9]
```diff
@@ -183,11 +328,7 @@ func (c *HTTPFacilitatorClient) GetSupported(ctx context.Context) (x402.Supporte
...
 		if resp.StatusCode == http.StatusOK {
-			var supportedResponse x402.SupportedResponse
-			if err := json.Unmarshal(responseBody, &supportedResponse); err != nil {
-				return x402.SupportedResponse{}, fmt.Errorf("failed to decode supported response: %w", err)
-			}
-			return supportedResponse, nil
+			return parseSupportedSuccessResponse(responseBody)
 		}
 
 		lastErr = fmt.Errorf("facilitator supported failed (%d): %s", resp.StatusCode, string(responseBody))
```
Comment (ethanoroshiba) [inline go/http/facilitator_client.go]: Might be good to use `responseExcerpt` here as well

**Review by ethanoroshiba — CHANGES_REQUESTED** [review]
Super big thanks for implementing the additional functionality. Just a few comments for you here, mostly nits. Also, `pnpm lint:check` and `pnpm format:check` aren't succeeding for me locally. If you haven't seen already, `typsecript/CONTRIBUTING.md` has a bunch of helpful `pnpm` commands to run before committing.

**Comment by ziyangliu-666** [comment]
Thanks for the review. I pushed a follow-up that fixes the init retry path, the ES2022 `Error.cause` build issue, and the `responseExcerpt` call sites, and I added regression coverage for the retry behavior. I also reran the relevant checks locally.

File: typescript/packages/http/express/src/index.ts (hunk 1 above)
Comment (ziyangliu-666) [reply typescript/packages/http/express/src/index.ts]: Kept this local for now to avoid expanding `@x402/core` for a wrapper-only helper. Happy to follow up separately if we want to consolidate it.

File: typescript/packages/http/express/src/index.ts (hunk 2 above)
Comment (ziyangliu-666) [reply typescript/packages/http/express/src/index.ts:153]: Fixed the retry path here. I didn’t take the literal `initPromise = null` suggestion as-is, since the promise was only created once; this now properly recreates init after failure.

File: go/http/facilitator_client.go (hunk 3 above)
Comment (ziyangliu-666) [reply go/http/facilitator_client.go]: Kept these helpers for now to keep the response normalization path compact. Happy to inline them if you feel strongly.

File: typescript/packages/http/hono/src/index.ts (hunk 5 above)
Comment (ziyangliu-666) [reply typescript/packages/http/hono/src/index.ts:154]: Fixed the retry path here as well.

File: typescript/packages/http/hono/src/index.ts (hunk 6 above)
Comment (ziyangliu-666) [reply typescript/packages/http/hono/src/index.ts]: Fixed by bumping the base `lib` to `ES2022` without changing the target.

File: typescript/packages/core/src/http/httpFacilitatorClient.ts (hunk 7 above)
Comment (ziyangliu-666) [reply typescript/packages/core/src/http/httpFacilitatorClient.ts]: Updated to use `responseExcerpt` here.

File: typescript/packages/core/src/http/httpFacilitatorClient.ts (hunk 8 above)
Comment (ziyangliu-666) [reply typescript/packages/core/src/http/httpFacilitatorClient.ts]: Updated to use `responseExcerpt` here as well.

File: go/http/facilitator_client.go (hunk 9 above)
Comment (ziyangliu-666) [reply go/http/facilitator_client.go]: Updated to use `responseExcerpt` here too.

File: typescript/packages/http/express/src/index.ts (hunk 1 above)
Comment (ziyangliu-666) [reply typescript/packages/http/express/src/index.ts]: Moved this to shared functionality in `@x402/core/server` and reused it across the wrappers.

File: go/http/facilitator_client.go (hunk 3 above)
Comment (ziyangliu-666) [reply go/http/facilitator_client.go]: Inlined these nil checks into the calling function.

File: go/http/facilitator_client.go (hunk 4 above)
Comment (ziyangliu-666) [reply go/http/facilitator_client.go]: Updated this wording to `invalid supported response fields` to make it broader without implying only missing fields.

**Review by ethanoroshiba — COMMENTED** [review]
Thanks for the work on this, all changes LGTM. Locally the Typescript SDK is still failing lint and format checks, would you mind addressing those before I merge?

**Comment by ziyangliu-666** [comment]
Sorry about that, and thanks for catching it. I pushed 41e357f8 to address the Typescript SDK lint/format failures from this PR, and also fixed a separate local formatting-check issue in @x402/aptos caused by dist/ artifacts being picked up. I reran pnpm lint:check and pnpm format:check under typescript/, and both are passing now.

**Comment by ziyangliu-666** [comment]
Rebased this PR onto the latest main and force-pushed the branch. Current head is bdf2bd47.

**Review by ethanoroshiba — APPROVED** [review]
