### PR TITLE
fix(ts:schemes): circular dep

### LINKED ISSUE #28: Circular Imports in Exact EVM Scheme Files
Running into some issues when depending on the `typescript/x402` package that are resolved by extracting the `encode`/`decode` functions in the `exact/evm` code into their own utils folder.

[Client Import](https://github.com/coinbase/x402/blob/main/packages/typescript/x402/src/schemes/exact/evm/client.ts#L5)
[Index Import](https://github.com/coinbase/x402/blob/main/packages/typescript/x402/src/schemes/exact/evm/index.ts#L5)

I'll push the fix soon but would like to get buy-in on resolving this issue.

### PR DESCRIPTION
**Pull request by Quazia**
fixes #28

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by John-peterson-coinbase — APPROVED** [review]

File: packages/typescript/x402/src/schemes/exact/evm/utils/paymentUtils.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
+import { paymentPayloadSchema } from "../types";
+import { safeBase64Encode, safeBase64Decode } from "../../../../shared";
+import { PaymentPayload } from "../../exact/evm/types";
```
Comment (John-peterson-coinbase) [inline packages/typescript/x402/src/schemes/exact/evm/utils/paymentUtils.ts]: Build fails with 

```
x402:build: src/schemes/exact/evm/utils/paymentUtils.ts(3,32): error TS2307: Cannot find module '../../exact/evm/types' or its corresponding type declarations.
x402:build: npm error Lifecycle script `build` failed with error:
x402:build: npm error code 2
x402:build: npm error path /vercel/path0/packages/typescript/x402
x402:build: npm error workspace x402@0.1.0
x402:build: npm error location /vercel/path0/packages/typescript/x402
x402:build: npm error command failed
x402:build: npm error command sh -c tsc
x402:build: ERROR: command finished with error: command (/vercel/path0/packages/typescript/x402) /node22/bin/npm run build exited (2)
x402#build: command (/vercel/path0/packages/typescript/x402) /node22/bin/npm run build exited (2)
```

**Review by John-peterson-coinbase — CHANGES_REQUESTED** [review]

File: packages/typescript/x402/src/schemes/exact/evm/utils/paymentUtils.ts (hunk 1 above)
Comment (Quazia) [reply packages/typescript/x402/src/schemes/exact/evm/utils/paymentUtils.ts]: Thanks! Resolved now - sorry I moved it around heh.

**Review by John-peterson-coinbase — APPROVED** [review]
